using System;
using System.Collections.Generic;

#nullable disable

namespace StudentAPI.Models
{
    public partial class Application
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Apt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public DateTime? Birthdate { get; set; }
        public int? Age { get; set; }
        public string StudentId { get; set; }
        public string Last4Ssn { get; set; }
        public string StudentCell { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public string Race { get; set; }
        public string Nationality { get; set; }
        public string Languages { get; set; }
        public bool? ReducedLunch { get; set; }
        public bool? Retained { get; set; }
        public string RetainedGrade { get; set; }
        public bool? Ibprogram { get; set; }
        public string IbprogramType { get; set; }
        public bool? Tsicprogram { get; set; }
        public string Tsictype { get; set; }
        public bool? GiftedChild { get; set; }
        public bool? Iepplan { get; set; }
        public string IeplanType { get; set; }
        public bool? AttendedFirewallBefore { get; set; }
        public string HearAboutUs { get; set; }
        public bool? KnowAnyoneAttending { get; set; }
        public string AttendingStudentName { get; set; }
        public string ParentName { get; set; }
        public string ParentMobile { get; set; }
        public string ParentRelationship { get; set; }
        public string ParentEmail { get; set; }
        public string ParentWorkPhone { get; set; }
        public string ParentEducatin { get; set; }
        public string ParentContactMethod { get; set; }
        public string Parent2Name { get; set; }
        public string Parent2Mobile { get; set; }
        public string Parent2Relationship { get; set; }
        public string Parent2Email { get; set; }
        public string Parent2WorkPhone { get; set; }
        public string Parent2Education { get; set; }
        public string Parent2ContactMethod { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string EmergencyContactRelations { get; set; }
        public string PickUpName { get; set; }
        public string PickUpMobile { get; set; }
        public string PickUpRelations { get; set; }
        public string PickUp2Name { get; set; }
        public string PickUp2Mobile { get; set; }
        public string PickUp2Relations { get; set; }
        public string PickUp3Name { get; set; }
        public string PickUp3Mobile { get; set; }
        public string PickUp3Relations { get; set; }
        public bool? AllowedToWalk { get; set; }
        public string EmergencyNotes { get; set; }
        public bool? HealthInssurance { get; set; }
        public string InsuranceCarrier { get; set; }
        public string PolicyNumber { get; set; }
        public bool? MedicalCondition { get; set; }
        public string MedicalConditionNotes { get; set; }
        public bool? TakingMedication { get; set; }
        public string TakingMedicationNotes { get; set; }
        public bool? SingleParent { get; set; }
        public string HouseHoldSize { get; set; }
        public string StudentLiveWith { get; set; }
        public string AnnualHouseHoldIncome { get; set; }
        public string MaritalStuatus { get; set; }
        public string Signature { get; set; }
        public string ApplicationStatus { get; set; }
        public string ParentLastName { get; set; }
        public string Parent2LastName { get; set; }
        public string EmergencyContactLastName { get; set; }
        public string Email { get; set; }
        public string PickUpLastName { get; set; }
        public string PickUp2LastName { get; set; }
        public string PickUp3LastName { get; set; }
        public bool? Hamother { get; set; }
        public bool? HastepMother { get; set; }
        public bool? Hafather { get; set; }
        public bool? HastepFather { get; set; }
        public bool? Hagrandparent { get; set; }
        public bool? HaauntUncle { get; set; }
        public bool? HafosterParent { get; set; }
        public bool? RaceAmericanIndian { get; set; }
        public bool? RaceBlackAfricanAmerican { get; set; }
        public bool? RaceAsian { get; set; }
        public bool? RacePacificIslander { get; set; }
        public bool? RaceWhi { get; set; }
        public string SignParente { get; set; }
        public DateTime? SignDate { get; set; }
        public string HomePhone { get; set; }
        public string EmergencyPhone { get; set; }
        public bool? BePickedUp { get; set; }
        public bool? Citybus { get; set; }
        public bool? FoodNutritional { get; set; }
        public bool? HealthInsurranceAsk { get; set; }
        public bool? Employment { get; set; }
        public bool? Counseling { get; set; }
        public bool? FinancialAssistance { get; set; }
        public bool? ChildCare { get; set; }
        public string CsOther { get; set; }
        public bool? Field504 { get; set; }
        public string SchoolYear { get; set; }
        public string DeniedReason { get; set; }
        public string ReferredBy { get; set; }
        public string Iep503bplan { get; set; }
        public bool? PreviuslyAttended { get; set; }
        public string HowFindAboutFirewall { get; set; }
    }
}
